services:
  - type: web
    name: legallens
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: UPLOAD_FOLDER
        value: ./uploads
      - key: REPORT_FOLDER
        value: ./reports
      - key: HISTORY_FOLDER
        value: ./history
      - key: FLASK_DEBUG
        value: "false"